# Dependabot configuration file
# Documentation: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
    # Limit to 10 open pull requests at any time
    open-pull-requests-limit: 10
    # Add assignees
    assignees:
      - "admin"
    # Add reviewers
    reviewers:
      - "admin"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "security"
    # Create a group of dependencies to be updated together
    groups:
      # Group production dependencies
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "eslint*"
          - "@types/*"
          - "typescript"
          - "jest*"
          - "@testing*"
          - "prettier"
      # Group development dependencies
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "eslint*"
          - "@types/*"
          - "typescript"
          - "jest*"
          - "@testing*"
          - "prettier"
    # Set security updates to high priority
    vulnerability-alerts: true
    # Specify the versioning strategy
    versioning-strategy: auto
    
  # Enable version updates for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "admin"
    reviewers:
      - "admin"
    labels:
      - "dependencies"
      - "security"
    groups:
      python-dependencies:
        patterns:
          - "*"
    vulnerability-alerts: true

  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    assignees:
      - "admin"
    reviewers:
      - "admin"
    labels:
      - "ci/cd"
      - "dependencies"
    vulnerability-alerts: true